CURRENT_ITEM = nil

ITEMS = {
    {"sand", "toggle"},
    {"growth", "toggle"},
    {"blaze", "toggle"},
    {"whirlwind", "toggle"},
    {"teleport", "toggle"},
    {"burst", "toggle"},
    {"lift", "toggle"},
    {"scoop", "toggle"},
    {"frost", "toggle"},
    {"grind", "toggle"},
    {"tremor", "toggle"},
    {"lash", "toggle"},
    {"carry", "toggle"},
    {"hover", "toggle"},
    {"pound", "toggle"},
    {"cyclone", "toggle"},
    {"force", "toggle"},
    {"douse", "toggle"},
    {"mars star", "toggle"},
    {"ruin key", "toggle"},
    {"red cloth", "toggle"},
    {"trident", "toggle"},
    {"sea god's tear", "toggle"},
    {"aquarius stone", "toggle"},
    {"black crystal", "toggle"},
    {"healing fungus", "toggle"},
    {"right prong", "toggle"},
    {"li'l turtle", "toggle"},
    {"large bread", "toggle"},
    {"shaman's rod", "toggle"},
    {"center prong", "toggle"},
    {"pretty stone", "toggle"},
    {"left prong", "toggle"},
    {"milk", "toggle"},
    {"magma ball", "toggle"},
    {"dancing idol", "toggle"},
    {"red key", "toggle"},
    {"blue key", "toggle"},
    {"lucky medal", "toggle"},
    {"azul", "toggle"},
    {"zagan", "toggle"},
    {"moloch", "toggle"},
    {"coatlicue", "toggle"},
    {"flora", "toggle"},
    {"iris", "toggle"},
    {"eclipse", "toggle"},
    {"charon", "toggle"},
    {"megaera", "toggle"},
    {"daedalus", "toggle"},
    {"catastrophe", "toggle"},
    {"haures", "toggle"},
    {"ulysses", "toggle"}
}

ITEMS_MAPPING = {
    [3717] = {"lash", "toggle"},
    [3718] = {"pound", "toggle"},
    [3726] = {"force", "toggle"},
    [3617] = {"douse", "toggle"},
    [3608] = {"frost", "toggle"},
    [3732] = {"catch", "toggle"}
}